export const siteConfig = {
  title: 'DevPath — Your developer growth path',
  description:
    'Curated roadmaps, guides, and tools to help you choose your path and level up as a developer.',
  url: {
    twitter: 'https://twitter.com/devpath',
    youtube: 'https://youtube.com/@devpath',
    repo: 'https://github.com/yourname/devpath',
    contribute: 'https://github.com/yourname/devpath/blob/main/contributing.md',
    issue: 'https://github.com/yourname/devpath/issues/new',
  },
  keywords: [
    'devpath',
    'developer roadmaps',
    'developer guides',
    'developer learning path',
    ...[
      'frontend developer',
      'backend developer',
      'sre',
      'devops',
      'android developer',
      'dba',
      'blockchain developer',
      'qa',
      'qa engineer',
      'software architect',
      'asp.net core developer',
      'react developer',
      'angular developer',
      'vue developer',
      'node.js developer',
      'javascript developer',
      'python developer',
      'go developer',
      'java developer',
      'design system',
      'software design',
      'graphql',
    ].flatMap((roadmapKeyword) => [
      `${roadmapKeyword} roadmap`,
      `${roadmapKeyword} roadmap 2025`,
    ]),
  ],
};
